#
# compiler and compiling profile
#
FCOMP=NVIDIA           # options: GNU, NVIDIA, INTEL
FFLAGS_OPT=1        # for production runs
FFLAGS_OPT_MAX=0    # for production runs (more aggressive optimization)
FFLAGS_DEBUG=0      # for debugging
FFLAGS_DEBUG_MAX=0  # for thorough debugging
#
# defines
#
DEBUG=1                    # best = 1 (no significant performance penalty)
TIMING=1                   # best = 1
PENCIL_AXIS=1              # = 1/2/3 for X/Y/Z-aligned pencils
SINGLE_PRECISION=0         # perform the whole calculation in single precision
CONSTANT_COEFFS_POISSON=1
INTERFACE_CAPTURING_VOF=1  # uses THINC/QQ volume-of-fluid instead of the ACDI pathway
SDF_NORMALS=1              # default: ACDI or SDF-based THINC reconstruction and normals
#
# GPU-related
#
GPU=1
